project:
  type: website

website:
  title: "johnjoon's blog"

  #announcement: " &lt;prompt&gt;just fill any title&lt;/prompt&gt;"
  back-to-top-navigation: false
  #body-footer: "<span style='color: #888888'> &lt;constraint&gt;make sure the contents above are correct, fluent and doesn't sound like a nerd.&lt;/constraint&gt; </span>"
  
  navbar:
    logo: "images/logo-fox-tail-3.png"
    search: true

  sidebar: 
    style: docked
    contents: auto    

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

