project:
  type: website
  preview:
    port: 7777

website:
  title: "johnjoon's blog"
  back-to-top-navigation: false
  navbar:
    logo: "images/profile.png"
    pinned: true
    search: true
    left: 
      - icon: house-door
        text: Home
        href: index.qmd
      - icon: book
        text: Blog
        href: blog.qmd
      - icon: briefcase
        text: Projects
        href: projects.qmd
      - icon: file-person
        text: About
        href: about.qmd
  # sidebar: 
  #   style: docked
  #   contents: auto
  page-footer:
    center: "[johnjoon's blog](https://johnjoon2004.github.io)© 2025 johnjoon2004 | Powered by [Quarto](https://quarto.org/)"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute: 
  freeze: auto