project:
  type: website

website:
  title: "johnjoon's Blog"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Posts
        href: posts/index.qmd

format:
  html:
    theme: cosmo
    toc: true
